services:
  ms-service-kuvera:
    build: .
    container_name: ms-service-kuvera
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    networks:
      - rjshub-network

networks:
  rjshub-network:
    name: 'rjshub-network'
    external: true
    driver: bridge